### ISSUE TITLE
TextInput component : add more prope

### ISSUE THREAD

**Issue by shubhamkakkar** [99xt/first-born#14]
It's not always that a user wants to have a rounded TextInput component, this could hence be updated for user code flexibility
( es6)
<TextInput /> : default, no styling
<TextInput bordered />  : bordered TextInput

and others like rounded and also custom styling liberty to user

**Comment by samsam-026** [comment]
Hi @shubhamkakkar,
I will soon do a review over the input components and let you know when a change is made.

**Comment by samsam-026** [comment]
Hi @shubhamkakkar,
I updated all Form Input Atoms to allow custom styles. To use it, you will need to first include the `noStyle` boolean prop, then include a style object for the following props;
`style`: the style of form Input in the inactive state
`activeStyle`: the style of form Input in the active state
`errorStyle`: the style of form Input when a validation error occurs.
