### ISSUE TITLE
Add support for error/feedback text in form fields?

### ISSUE THREAD

**Issue by sudomann** [99xt/first-born#15]
Currently there is no way to insert my own error text below each field since their render methods aren't exposed.

**Comment by samsam-026** [comment]
Hi @sudomann,
That feature has not been implemented yet. I will include an update here, when it's done.

**Comment by samsam-026** [comment]
Hi @sudomann,
This feature is now implemented in release v1.1.3. The `errorMessage` prop is a string that displays if the `isValid` prop function returns a false. The 'errorColor' prop allows you to define the color of the text and input when the validation fails
