### ISSUE TITLE
NavBarButton warning - requires unique keys

### ISSUE THREAD

**Issue by samsam-026** [99xt/first-born#16]
**Describe the bug**
A warning is displayed stating a child array of the NavBarButton component requires unique keys.

**To Reproduce**
Use the NavBarButton component in the NavBar organism.

**Expected behavior**
No warning is to be displayed

**Screenshots**
![1559018026304](https://user-images.githubusercontent.com/24349997/58451902-fc22d580-8132-11e9-9740-1139083059a6.JPEG)

**Smartphone (please complete the following information):**
 - OS: Android and iOS

**Comment by atsutton** [comment]
Hey @samsam-026 , can I take a crack at this?

**Comment by samsam-026** [comment]
> Hey @samsam-026 , can I take a crack at this?

Sure, Go ahead. 
Please do have a look at the contributing guidelines, before you do so. 
Thanks!

**Comment by atsutton** [comment]
Hey @samsam-026 - please check pull request #20

**Comment by samsam-026** [comment]
Fixed in pull request #20.
