### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by dixitabhishek63** [99xt/first-born#8]
**Describe the bug**
Unable to use Icon,eg  <Icon name="heart" color="red" /> works fine but  <Icon name="logout" color="red" /> shows just ? symbol

**To Reproduce**
i am using Icon inside NavBarButon

Sorry not a bug..help needed!

**Expected behavior**
Should show logout symbol

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 8.1

**Smartphone (please complete the following information):**
 - Device: Pixel2
 - OS: Android
 - Version Pie

**Comment by samsam-026** [comment]
Hi @dixitabhishek63. what was the value of the name property of the Icon? Also add the NavBarButton Code, please.

If its the logout symbol you want, try this.

```js
<Icon name="log-out" />
```
This will render different icons according to the platform.

**Comment by dixitabhishek63** [comment]
Thanks @samsam-026 for the response..sorry it was marked as a bug,it was rather a help needed kind of issue...I was trying to use "logout" symbol from any design,from what I understood, only Ionicons were available current in firstborn library...I will try it out...btw the library is working great for me...

**Comment by samsam-026** [comment]
No problem, @dixitabhishek63. Icon now supports all icons fonts, so have a quick look at the new usage if you wish to use a different icon set than Ionicon.
